export interface Book {
    id: number;
    name: string;
    author: string;
    price: number;
    img: string;
    description?: string;
  }

export const books: { category: string; categoryId?:number,items: Book[] }[] = [
    {
      category: "Best Seller",
      categoryId:1,
      items: [
        {
          id: 1,
          name: "Dune",
          author: "Frank Herbert",
          price: 87.75,
          img: "/images/dune.png",
          description: "Dune is set in the distant future amidst a feudal interstellar society in which various noble houses control planetary fiefs. It tells the story of young Paul Atreides, whose family accepts the stewardship of the planet Arrakis. While the planet is an inhospitable and sparsely populated desert wasteland, it is the only source of melange, or 'spice', a drug that extends life and enhances mental abilities. Melange is also necessary for space navigation, which requires a kind of multidimensional awareness and foresight that only the drug provides. As melange can only be produced on Arrakis, control of the planet is a coveted and dangerous undertaking. The story explores the multilayered interactions of politics, religion, ecology, technology, and human emotion, as the factions of the empire confront each other in a struggle for the control of Arrakis and its spice.",
        },
        {
          id: 2,
          name: "1984",
          author: "George Orwell",
          price: 37.75,
          img: "/images/1984.png",
          description: "George Orwell's 1984 is a dystopian novel set in a totalitarian regime where the Party, led by the figurehead Big Brother, exerts total control over all aspects of life. The story follows Winston Smith, a low-ranking member of the Party who works at the Ministry of Truth, where he alters historical records to fit the Party s propaganda. Winston secretly rebels against the oppressive system by starting a forbidden relationship with Julia and seeking the truth about the Party's manipulation. However, his attempts to defy the regime lead to his capture, torture, and eventual betrayal. The novel explores themes of surveillance, censorship, and the erasure of personal freedom, presenting a chilling vision of a future where individuality and truth are systematically obliterated",
        },
        {
          id: 3,
          name: "Ikıgai",
          author: "Hector Garcia",
          price: 36.00,
          img: "/images/ikigai.png",
          description: "Ikigai: The Japanese Secret to a Long and Happy Life by Hector Garcia explores the Japanese concept of ikigai, which refers to the reason one gets up in the morning and the joy that comes from living a fulfilling life. The book delves into how this philosophy contributes to a longer, more contented life, using insights from the residents of Okinawa, a region known for its high number of centenarians. Garcia and co-author Francesc Miralles provide practical advice on how to find one's own ikigai through passion, mission, vocation, and profession. By blending personal anecdotes, cultural insights, and research, the book offers readers a guide to discovering their purpose and achieving greater satisfaction in life.",
        },
        {
          id: 4,
          name: "Metafizik",
          author: "Aristoteles",
          price: 36.00,
          img: "/images/metafizik.png",
          description: "Aristotle's Metaphysics is a foundational philosophical text that explores the nature of reality, existence, and the fundamental principles underlying everything. The work is divided into several books, each addressing different aspects of metaphysics. Key topics include the concept of being, the nature of substance, causality, and the study of the first philosophy, which is concerned with the principles of reality beyond the physical world. Aristotle investigates the essence of objects, the concept of potentiality and actuality, and the nature of change. His exploration of these themes lays the groundwork for much of Western philosophical thought and continues to influence contemporary discussions on ontology and epistemology.",
        },
        {
          id: 13,
          name: "Suç Ve Ceza",
          author: "Fyodor Dostoyevski",
          price: 87.75,
          img: "/images/sucveceza.png",
          description: "Crime and Punishment by Fyodor Dostoevsky, first published in 1866, is a seminal work of Russian literature. The novel follows Rodion Raskolnikov, a impoverished student who believes himself superior and justifies committing a murder to improve his circumstances. The story explores his psychological turmoil and moral dilemmas as he grapples with guilt and redemption. Through Raskolnikov’s internal struggle and interactions with other characters, Dostoevsky delves into themes of justice, morality, and the human condition. A profound examination of crime and its consequences, it remains a timeless classic in the study of psychological and philosophical literature.",
        },
        {
          id: 14,
          name: "Gurur Ve Önyargı",
          author: "Jane Austen",
          price: 35.75,
          img: "/images/gururveonyargi.png",
          description: "Pride and Prejudice, written by Jane Austen and first published in 1813, is a beloved classic of English literature. Set in the early 19th century, the novel centers on Elizabeth Bennet, a sharp-witted and independent young woman, and her evolving relationship with the wealthy but aloof Mr. Darcy. Through its witty dialogue and keen social observations, Austen explores themes of class, marriage, and individual character. The story is celebrated for its rich characterization, clever commentary on societal norms, and the transformative journey of its protagonists. As one of Austen’s most acclaimed works, Pride and Prejudice continues to captivate readers with its enduring charm and insight into human nature.",
        },
        {
          id: 15,
          name: "Büyük Umutlar",
          author: "Charles Dickens",
          price: 36.00,
          img: "/images/buyukumutlar.png",
          description: "Great Expectations, penned by Charles Dickens and first published in 1861, is a compelling novel of personal development and social criticism. The story follows Pip, an orphaned boy who unexpectedly receives a fortune from an anonymous benefactor, leading him to London and a life of newfound privilege. As Pip matures, he grapples with his own values and the complexities of social class, love, and identity. Through its richly drawn characters and intricate plot, Dickens examines themes of ambition, redemption, and the impact of societal expectations. Great Expectations remains a profound and enduring exploration of human growth and moral integrity.",
        },
        {
          id: 18,
          name: "Küçük Prens",
          author: "Antonio De Saint",
          price: 87.75,
          img: "/images/kucukprens.png",
          description: "The Little Prince (Le Petit Prince), written by Antoine de Saint-Exupéry and first published in 1943, is a poignant and philosophical novella that has enchanted readers of all ages. The story follows a young, otherworldly prince who travels from planet to planet, meeting various inhabitants and learning profound lessons about life, love, and human nature. Through his encounters, the Little Prince discovers the importance of relationships and the essence of what truly matters, revealing insights that resonate deeply with readers. The book is celebrated for its simple yet profound storytelling, whimsical illustrations, and its exploration of themes such as innocence, friendship, and the search for meaning.",
        },
        {
          id: 19,
          name: "Matilda",
          author: "Roald Dahl",
          price: 35.75,
          img: "/images/matilda.png",
          description: "Matilda Wormwood is an extraordinary young girl with a brilliant mind and a love for reading. Despite her parents' neglect and the oppressive atmosphere at school, Matilda discovers she possesses telekinetic powers. As she learns to harness her abilities, she uses them to stand up against the cruel headmistress, Miss Trunchbull, and to bring about positive changes in her life and the lives of those around her. With Dahl's signature wit and imagination, Matilda is a captivating story of intelligence, resilience, and the triumph of good over evil.",
        },
      ],
    },
    {
      category: "Classics",
      categoryId:2,
      items: [
        {
          id: 5,
          name: "Romeo Ve Juliet",
          author: "William Shakespeare",
          price: 87.75,
          img: "/images/romeovejuliet.png",
          description: "William Shakespeare's Romeo and Juliet is a tragic play set in Verona, Italy, and tells the story of two young lovers from feuding families. Romeo Montague and Juliet Capulet fall deeply in love despite the enmity between their families. They secretly marry, hoping to unite their warring households. However, a series of unfortunate events, including a street fight that leads to Romeo's banishment and a failed plan to reunite with Juliet, culminate in their tragic deaths. The play explores themes of love, fate, and the impact of family conflict, ultimately illustrating how the intense passion of the young lovers leads to both their own demise and the reconciliation of their feuding families",
        },
        {
          id: 6,
          name: "Olağan Üstü Bir Gece",
          author: "Stefan Zweig",
          price: 35.75,
          img: "/images/olaganustubirgece.png",
          description: "Stefan Zweig's Beware of Pity is a novel that delves into the complexities of human emotions and relationships. Set in the early 20th century, the story follows a young Austrian cavalry officer who becomes entangled in the life of a woman named Edith, who is paralyzed from the waist down. Initially motivated by pity and a desire to alleviate her suffering, the officer finds himself increasingly drawn into a complicated emotional web. As he navigates his own feelings of guilt, compassion, and desire, the consequences of his actions lead to a dramatic and unforeseen climax. The novel explores themes of empathy, moral responsibility, and the consequences of emotional decisions.",
        },
        {
          id: 7,
          name: "Genç Werther'in Acıları",
          author: "Goethe",
          price: 36.00,
          img: "/images/gencwerther.jpg",
          description: "Johann Wolfgang von Goethe’s The Sorrows of Young Werther is an epistolary novel that follows the passionate and tragic experiences of Werther, a young artist. Set in the late 18th century, the story is told through Werther’s letters to his friend Wilhelm. Werther falls deeply in love with Charlotte, a woman who is already engaged to another man. His unrequited love and the emotional turmoil it causes lead him into a profound despair. As Werther’s obsession with Charlotte grows, he becomes increasingly despondent and isolated, culminating in a heart-wrenching conclusion. The novel explores themes of love, longing, and the impact of unfulfilled desires, and it is a key work of the Romantic literary movement.",
        },
        {
          id: 8,
          name: "Zaman Makinesi",
          author: "H.G Wells",
          price: 36.00,
          img: "/images/zamanmakinesi.png",
          description: "H.G. Wells' The Time Machine is a seminal science fiction novel that follows the adventures of an unnamed Time Traveller who invents a machine capable of traveling through time. In the late 19th century, he uses this machine to journey far into the future, where he encounters two distinct species: the Eloi, a gentle and passive race living in apparent ease, and the Morlocks, subterranean beings who maintain the machinery of the Eloi's world. As he explores this future world, he discovers the consequences of social and technological evolution. The novel delves into themes of progress, class struggle, and the potential destiny of humanity, offering a thought-provoking exploration of time and societal development.",
        },
        {
          id: 13,
          name: "Suç Ve Ceza",
          author: "Fyodor Dostoyevski",
          price: 87.75,
          img: "/images/sucveceza.png",
          description: "Crime and Punishment by Fyodor Dostoevsky, first published in 1866, is a seminal work of Russian literature. The novel follows Rodion Raskolnikov, a impoverished student who believes himself superior and justifies committing a murder to improve his circumstances. The story explores his psychological turmoil and moral dilemmas as he grapples with guilt and redemption. Through Raskolnikov’s internal struggle and interactions with other characters, Dostoevsky delves into themes of justice, morality, and the human condition. A profound examination of crime and its consequences, it remains a timeless classic in the study of psychological and philosophical literature.",
        },
        {
          id: 14,
          name: "Gurur Ve Önyargı",
          author: "Jane Austen",
          price: 35.75,
          img: "/images/gururveonyargi.png",
          description: "Pride and Prejudice, written by Jane Austen and first published in 1813, is a beloved classic of English literature. Set in the early 19th century, the novel centers on Elizabeth Bennet, a sharp-witted and independent young woman, and her evolving relationship with the wealthy but aloof Mr. Darcy. Through its witty dialogue and keen social observations, Austen explores themes of class, marriage, and individual character. The story is celebrated for its rich characterization, clever commentary on societal norms, and the transformative journey of its protagonists. As one of Austen’s most acclaimed works, Pride and Prejudice continues to captivate readers with its enduring charm and insight into human nature.",
        },
        {
          id: 15,
          name: "Büyük Umutlar",
          author: "Charles Dickens",
          price: 36.00,
          img: "/images/buyukumutlar.png",
          description: "Great Expectations, penned by Charles Dickens and first published in 1861, is a compelling novel of personal development and social criticism. The story follows Pip, an orphaned boy who unexpectedly receives a fortune from an anonymous benefactor, leading him to London and a life of newfound privilege. As Pip matures, he grapples with his own values and the complexities of social class, love, and identity. Through its richly drawn characters and intricate plot, Dickens examines themes of ambition, redemption, and the impact of societal expectations. Great Expectations remains a profound and enduring exploration of human growth and moral integrity.",
        },
        {
          id: 16,
          name: "Yüzüklerin Efendisi",
          author: "H.G Wells",
          price: 36.75,
          img: "/images/yuzuklerinefendisi.png",
          description: "The Lord of the Rings, written by J.R.R. Tolkien and published in three volumes between 1954 and 1955, is an epic fantasy saga set in the richly imagined world of Middle-earth. The story follows the journey of Frodo Baggins, a humble hobbit tasked with destroying a powerful and malevolent ring that threatens the world with darkness. Alongside a diverse fellowship of characters, Frodo faces numerous challenges and battles against the dark forces of Sauron. The trilogy explores themes of heroism, friendship, and the struggle between good and evil, and is renowned for its intricate world-building, mythic depth, and enduring impact on the fantasy genre.",
        },
        {
          id: 17,
          name: "Don Kişot",
          author: "Miguel De Cervantes",
          price: 35.00,
          img: "/images/donkisot.png",
          description: "Don Quixote, written by Miguel de Cervantes and first published in two parts in 1605 and 1615, is a seminal work in Western literature. The novel follows the adventures of Alonso Quixano, a gentleman from La Mancha who, inspired by chivalric romances, becomes Don Quixote and sets out to revive knighthood and justice. Accompanied by his loyal squire, Sancho Panza, Don Quixote's idealistic quests often lead to comical and poignant encounters, as he battles perceived injustices and confronts the gap between reality and illusion. Cervantes' masterful blend of satire, humor, and profound social commentary makes Don Quixote a timeless exploration of human nature, imagination, and the power of dreams.",
        },
      ],
    },
    {
      category: "Children",
      categoryId:3,
      items: [
        {
          id: 9,
          name: "Mor Bir Fil Gördüm Sanki",
          author: "Varol Yaşaroğlu",
          price: 87.75,
          img: "/images/morbirfil.png",
          description: "Mor Bir Fil Gördüm Sanki (I Think I Saw a Purple Elephant) by Varol Yaşaroğlu is a novel that explores themes of reality and imagination through an unconventional narrative. The story revolves around the experiences and reflections of the protagonist as they navigate a world where the boundaries between fantasy and reality blur. The book delves into the protagonist’s inner struggles, societal observations, and personal growth, often using surreal and symbolic elements to challenge conventional perspectives. Through its unique storytelling and thematic depth, the novel invites readers to question their perceptions and explore the nature of existence.",
        },
        {
          id: 10,
          name: "Alev Saçlı Çocuk",
          author: "Christine Nöstlinger",
          price: 35.75,
          img: "/images/alevsaclicocuk.png",
          description: "Christine Nöstlinger’s The Fire Hair Child tells the story of a young boy named Bimbo, who has bright red hair and a vivid imagination. Set in a city where Bimbo feels out of place due to his unique appearance, he embarks on a series of adventures that reveal his inner strength and creativity. The narrative explores themes of individuality, self-acceptance, and the challenges of growing up. Through Bimbo’s journey, Nöstlinger addresses the importance of embracing one’s uniqueness and finding one’s place in a world that often values conformity.",
        },
        {
          id: 11,
          name: "Melodi",
          author: "Anıl Basılı",
          price: 36.00,
          img: "/images/melodi.png",
          description: "Melodi by Anıl Basılı is a poignant novel that explores the life and emotions of its protagonist, Melodi, a young woman who faces personal and societal challenges. The story delves into Melodi’s struggles with her identity, relationships, and aspirations as she navigates a complex world. Through her journey, the novel addresses themes of self-discovery, resilience, and the quest for personal fulfillment. Basılı’s narrative is both introspective and engaging, providing readers with a deep understanding of Melodi’s character and the obstacles she encounters.",
        },
        {
          id: 12,
          name: "Siber Kahramanlar",
          author: "Feyza Şahin",
          price: 36.00,
          img: "/images/siberkahramanlar.png",
          description: "Siber Kahramanlar (Cyber Heroes) by Feyza Şahin is a gripping novel set in the digital age, focusing on a group of young individuals who become cyber activists. As they navigate the challenges of modern technology and online threats, they take on the roles of digital heroes fighting against cybercrime and injustice. The story combines elements of adventure and technology, exploring themes of bravery, ethical dilemmas, and the impact of technology on society. Through the experiences of these cyber heroes, Şahin addresses contemporary issues related to cybersecurity, privacy, and the power of collective action in the digital world.",
        },
        {
          id: 18,
          name: "Küçük Prens",
          author: "Antonio De Saint",
          price: 87.75,
          img: "/images/kucukprens.png",
          description: "The Little Prince (Le Petit Prince), written by Antoine de Saint-Exupéry and first published in 1943, is a poignant and philosophical novella that has enchanted readers of all ages. The story follows a young, otherworldly prince who travels from planet to planet, meeting various inhabitants and learning profound lessons about life, love, and human nature. Through his encounters, the Little Prince discovers the importance of relationships and the essence of what truly matters, revealing insights that resonate deeply with readers. The book is celebrated for its simple yet profound storytelling, whimsical illustrations, and its exploration of themes such as innocence, friendship, and the search for meaning.",
        },
        {
          id: 19,
          name: "Matilda",
          author: "Roald Dahl",
          price: 35.75,
          img: "/images/matilda.png",
          description: "Matilda Wormwood is an extraordinary young girl with a brilliant mind and a love for reading. Despite her parents' neglect and the oppressive atmosphere at school, Matilda discovers she possesses telekinetic powers. As she learns to harness her abilities, she uses them to stand up against the cruel headmistress, Miss Trunchbull, and to bring about positive changes in her life and the lives of those around her. With Dahl's signature wit and imagination, Matilda is a captivating story of intelligence, resilience, and the triumph of good over evil.",
        },
        {
          id: 20,
          name: "Bambi",
          author: "Felix Salten",
          price: 36.00,
          img: "/images/bambi.png",
          description: "Bambi: A Life in the Woods is a timeless tale that follows the life of a young deer named Bambi as he grows up in the forest. Written by Felix Salten, this classic novel delves into the beauty and harsh realities of nature through Bambi's experiences. As Bambi matures, he encounters various challenges and learns about the cycle of life, the importance of family, and the struggles of survival. Salten's evocative prose and deep understanding of the natural world create a poignant and memorable story that explores themes of growth, loss, and the interconnectedness of all living things.",
        },
      ],
    },
    {
      category: "Other",
      categoryId:4,
      items: [
        {
          id: 13,
          name: "Suç Ve Ceza",
          author: "Fyodor Dostoyevski",
          price: 87.75,
          img: "/images/sucveceza.png",
          description: "Crime and Punishment by Fyodor Dostoevsky, first published in 1866, is a seminal work of Russian literature. The novel follows Rodion Raskolnikov, a impoverished student who believes himself superior and justifies committing a murder to improve his circumstances. The story explores his psychological turmoil and moral dilemmas as he grapples with guilt and redemption. Through Raskolnikov’s internal struggle and interactions with other characters, Dostoevsky delves into themes of justice, morality, and the human condition. A profound examination of crime and its consequences, it remains a timeless classic in the study of psychological and philosophical literature.",
        },
        {
          id: 14,
          name: "Gurur Ve Önyargı",
          author: "Jane Austen",
          price: 35.75,
          img: "/images/gururveonyargi.png",
          description: "Pride and Prejudice, written by Jane Austen and first published in 1813, is a beloved classic of English literature. Set in the early 19th century, the novel centers on Elizabeth Bennet, a sharp-witted and independent young woman, and her evolving relationship with the wealthy but aloof Mr. Darcy. Through its witty dialogue and keen social observations, Austen explores themes of class, marriage, and individual character. The story is celebrated for its rich characterization, clever commentary on societal norms, and the transformative journey of its protagonists. As one of Austen’s most acclaimed works, Pride and Prejudice continues to captivate readers with its enduring charm and insight into human nature.",
        },
        {
          id: 15,
          name: "Büyük Umutlar",
          author: "Charles Dickens",
          price: 36.00,
          img: "/images/buyukumutlar.png",
          description: "Great Expectations, penned by Charles Dickens and first published in 1861, is a compelling novel of personal development and social criticism. The story follows Pip, an orphaned boy who unexpectedly receives a fortune from an anonymous benefactor, leading him to London and a life of newfound privilege. As Pip matures, he grapples with his own values and the complexities of social class, love, and identity. Through its richly drawn characters and intricate plot, Dickens examines themes of ambition, redemption, and the impact of societal expectations. Great Expectations remains a profound and enduring exploration of human growth and moral integrity.",
        },
        {
          id: 16,
          name: "Yüzüklerin Efendisi",
          author: "H.G Wells",
          price: 36.75,
          img: "/images/yuzuklerinefendisi.png",
          description: "The Lord of the Rings, written by J.R.R. Tolkien and published in three volumes between 1954 and 1955, is an epic fantasy saga set in the richly imagined world of Middle-earth. The story follows the journey of Frodo Baggins, a humble hobbit tasked with destroying a powerful and malevolent ring that threatens the world with darkness. Alongside a diverse fellowship of characters, Frodo faces numerous challenges and battles against the dark forces of Sauron. The trilogy explores themes of heroism, friendship, and the struggle between good and evil, and is renowned for its intricate world-building, mythic depth, and enduring impact on the fantasy genre.",
        },
        {
          id: 17,
          name: "Don Kişot",
          author: "Miguel De Cervantes",
          price: 35.00,
          img: "/images/donkisot.png",
          description: "Don Quixote, written by Miguel de Cervantes and first published in two parts in 1605 and 1615, is a seminal work in Western literature. The novel follows the adventures of Alonso Quixano, a gentleman from La Mancha who, inspired by chivalric romances, becomes Don Quixote and sets out to revive knighthood and justice. Accompanied by his loyal squire, Sancho Panza, Don Quixote's idealistic quests often lead to comical and poignant encounters, as he battles perceived injustices and confronts the gap between reality and illusion. Cervantes' masterful blend of satire, humor, and profound social commentary makes Don Quixote a timeless exploration of human nature, imagination, and the power of dreams.",
        },
        {
          id: 18,
          name: "Küçük Prens",
          author: "Antonio De Saint",
          price: 87.75,
          img: "/images/kucukprens.png",
          description: "The Little Prince (Le Petit Prince), written by Antoine de Saint-Exupéry and first published in 1943, is a poignant and philosophical novella that has enchanted readers of all ages. The story follows a young, otherworldly prince who travels from planet to planet, meeting various inhabitants and learning profound lessons about life, love, and human nature. Through his encounters, the Little Prince discovers the importance of relationships and the essence of what truly matters, revealing insights that resonate deeply with readers. The book is celebrated for its simple yet profound storytelling, whimsical illustrations, and its exploration of themes such as innocence, friendship, and the search for meaning.",
        },
        {
          id: 19,
          name: "Matilda",
          author: "Roald Dahl",
          price: 35.75,
          img: "/images/matilda.png",
          description: "Matilda Wormwood is an extraordinary young girl with a brilliant mind and a love for reading. Despite her parents' neglect and the oppressive atmosphere at school, Matilda discovers she possesses telekinetic powers. As she learns to harness her abilities, she uses them to stand up against the cruel headmistress, Miss Trunchbull, and to bring about positive changes in her life and the lives of those around her. With Dahl's signature wit and imagination, Matilda is a captivating story of intelligence, resilience, and the triumph of good over evil.",
        },
        {
          id: 20,
          name: "Bambi",
          author: "Felix Salten",
          price: 36.00,
          img: "/images/bambi.png",
          description: "Bambi: A Life in the Woods is a timeless tale that follows the life of a young deer named Bambi as he grows up in the forest. Written by Felix Salten, this classic novel delves into the beauty and harsh realities of nature through Bambi's experiences. As Bambi matures, he encounters various challenges and learns about the cycle of life, the importance of family, and the struggles of survival. Salten's evocative prose and deep understanding of the natural world create a poignant and memorable story that explores themes of growth, loss, and the interconnectedness of all living things.",
        },
      ],
    },
  ];